language: node_js
node_js: 10
script: npm run test
notifications:
  email: false
  
deploy:
provider: pages
skip_cleanup: true
github_token: $GH_TOKEN
local_dir: dist
on:
  branch: master

after_success:  
- cd ./dist
- git init
- git add .
- git commit -m "Automatically update from travis-ci"
- git push --quiet --force  "https://$GH_TOKEN@$GH_REF" master:${P_BRANCH}